# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      go-major:
        applies-to: version-updates
        update-types:
          - "major"
  - package-ecosystem: "npm"
    directory: "/cmd/gui/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      npm-major:
        applies-to: version-updates
        update-types:
          - "major"
