// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function Unlock(arg1, arg2) {
  return window['go']['main']['App']['Unlock'](arg1, arg2);
}
