// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function AppInfo():Promise<Record<string, string>>;

export function ClipboardClearSeconds():Promise<number>;

export function ChangeLockPassword(arg1:string):Promise<void>;

export function CloneStore(arg1:string,arg2:string):Promise<void>;

export function CopyPassword(arg1:string):Promise<void>;

export function CreatePassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CurrentSettings():Promise<ui.SettingsInfo>;

export function ImportPGPKeyFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ImportSSHKeyFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HasSSHKeyLoaded():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function KnownHosts():Promise<Array<string>>;

export function ListPasswords():Promise<Array<string>>;

export function LoadSSHKey(arg1:string):Promise<void>;

export function Lock():Promise<void>;

export function OpenLocalStore(arg1:string):Promise<void>;

export function PickPrivateKey(arg1:string):Promise<ui.Picked>;

export function PickStoreDir():Promise<ui.Picked>;

export function PrepareClone(arg1:string):Promise<ui.ClonePrep>;

export function RemovePassword(arg1:string):Promise<void>;

export function SetAutoLock(arg1:number):Promise<void>;

export function SetClipboardClear(arg1:number):Promise<void>;

export function SetGitAuthor(arg1:string,arg2:string):Promise<void>;

export function ShowPassword(arg1:string):Promise<string>;

export function Status():Promise<string>;

export function StoredStores():Promise<Array<string>>;

export function Sync():Promise<string>;

export function TrustHost(arg1:string):Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdatePassword(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;
