// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ClipboardClearSeconds() {
  return window['go']['main']['App']['ClipboardClearSeconds']();
}

export function CopyPassword(arg1) {
  return window['go']['main']['App']['CopyPassword'](arg1);
}

export function CreatePassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePassword'](arg1, arg2, arg3, arg4);
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListPasswords() {
  return window['go']['main']['App']['ListPasswords']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function RemovePassword(arg1) {
  return window['go']['main']['App']['RemovePassword'](arg1);
}

export function ShowPassword(arg1) {
  return window['go']['main']['App']['ShowPassword'](arg1);
}

export function Unlock(arg1, arg2) {
  return window['go']['main']['App']['Unlock'](arg1, arg2);
}

export function UpdatePassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePassword'](arg1, arg2, arg3, arg4);
}
