// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo():Promise<Record<string, string>>;

export function IsUnlocked():Promise<boolean>;

export function Lock():Promise<void>;

export function Unlock(arg1:string,arg2:string):Promise<void>;
