// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo():Promise<Record<string, string>>;

export function ClipboardClearSeconds():Promise<number>;

export function CopyPassword(arg1:string):Promise<void>;

export function CreatePassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function IsUnlocked():Promise<boolean>;

export function ListPasswords():Promise<Array<string>>;

export function Lock():Promise<void>;

export function RemovePassword(arg1:string):Promise<void>;

export function ShowPassword(arg1:string):Promise<string>;

export function Unlock(arg1:string,arg2:string):Promise<void>;

export function UpdatePassword(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;
